/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#006a2d",
        "surface-variant": "#142156",
        "error-container": "#9f0519",
        "primary-fixed": "#6e9fff",
        "on-tertiary": "#00692c",
        "inverse-primary": "#005bc4",
        "on-secondary-fixed": "#4f0089",
        "secondary-fixed-dim": "#dbb4ff",
        "surface-container-low": "#050f38",
        "secondary": "#c180ff",
        "surface-tint": "#85adff",
        "on-secondary-fixed-variant": "#7511c3",
        "on-tertiary-fixed": "#004a1d",
        "primary-fixed-dim": "#5391ff",
        "surface-container": "#091542",
        "outline": "#6b739d",
        "tertiary-container": "#6bff8f",
        "primary": "#85adff",
        "on-primary": "#002c66",
        "on-primary-container": "#002150",
        "on-tertiary-container": "#005f28",
        "surface-bright": "#192760",
        "inverse-surface": "#fbf8ff",
        "on-secondary-container": "#e9cdff",
        "error": "#ff716c",
        "error-dim": "#d7383b",
        "background": "#020a2f",
        "secondary-fixed": "#e5c6ff",
        "on-surface": "#e1e4ff",
        "on-secondary": "#33005b",
        "secondary-dim": "#9c48ea",
        "secondary-container": "#6f00be",
        "surface-dim": "#020a2f",
        "surface-container-high": "#0e1b4c",
        "on-error": "#490006",
        "primary-dim": "#699cff",
        "on-surface-variant": "#a1a9d5",
        "on-error-container": "#ffa8a3",
        "inverse-on-surface": "#4b537a",
        "tertiary-fixed": "#6bff8f",
        "tertiary-dim": "#5bf083",
        "surface": "#020a2f",
        "tertiary": "#c5ffc9",
        "primary-container": "#6e9fff",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#142156",
        "tertiary-fixed-dim": "#5bf083",
        "outline-variant": "#3d466c",
        "on-primary-fixed-variant": "#002a62",
        "on-background": "#e1e4ff",
        "on-primary-fixed": "#000000"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}